In [1]:
 #Exp :- 5

In [2]:
#Aim: To perform Operation of Statistical description

In [3]:
#Name:Bhavesh Chafekar
#Roll:09
#sec:C
#subject:DSS
#Date:-07-2006

In [4]:
import pandas as pd

In [5]:
import os

In [6]:
os.getcwd()

'C:\\Users\\BHAVESH'

In [7]:
os.chdir("C:\\Users\\BHAVESH\\OneDrive\\Pictures\\Desktop")

In [8]:
data=pd.read_csv("pandu.csv")

In [9]:
data.head()

   No        Name  Type1   Type2  Height  Weight  Legendary
0   1   Bulbasaur  Grass  Poison     0.7     6.9          0
1   2     Ivysaur  Grass  Poison     1.0    13.0          0
2   3    Venusaur  Grass  Poison     2.0   100.0          0
3   4  Charmander   Fire     NaN     0.6     8.5          0
4   5  Charmeleon   Fire     NaN     1.1    19.0          0

In [10]:
data.tail()

      No       Name    Type1   Type2  Height  Weight  Legendary
145  146    Moltres     Fire  Flying     2.0    60.0          1
146  147    Dratini   Dragon     NaN     1.8     3.3          0
147  148  Dragonair   Dragon     NaN     4.0    16.5          0
148  149  Dragonite   Dragon  Flying     2.2   210.0          0
149  150     Mewtwo  Psychic     NaN     2.0   122.0          1

In [11]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 150 entries, 0 to 149
Data columns (total 7 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   No         150 non-null    int64
 1   Name       150 non-null    object
 2   Type1      150 non-null    object
 3   Type2      67 non-null     object
 4   Height     150 non-null    float64
 5   Weight     150 non-null    float64
 6   Legendary  150 non-null    int64
dtypes: float64(2), int64(2), object(3)
memory usage: 8.3+ KB

In [12]:
data.describe()

               No      Height      Weight   Legendary
count  150.000000  150.000000  150.000000  150.000000
mean    75.500000    1.200000   46.231333    0.026667
std     43.445368    0.963634   59.547388    0.161647
min      1.000000    0.200000    0.100000    0.000000
25%     38.250000    0.700000    9.925000    0.000000
50%     75.500000    1.000000   30.000000    0.000000
75%    112.750000    1.500000   56.375000    0.000000
max    150.000000    8.800000  460.000000    1.000000

In [13]:

data.mean()

TypeError: can only concatenate str (not "int") to str

In [ ]:
data.median()

In [ ]:
data.std()

In [ ]:
data.var()